version: '3.8'

services:
  mongo:
    image: mongo:5.0.0
    environment:
      - MONGO_URL=mongodb://mongo:27017/dev
    volumes:
      - ./data/mongo:/data/db:delegated
    ports:
      - 27017:27017
  node:
    image: node:22
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/dev
      - PORT=3000
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    entrypoint:
        - /bin/sh
        - -c
        - |
            cd /app && \
            npm install && \
            npm run dev:logistic:backend

volumes:
  node_modules:
